### check health
GET http://localhost:8060/health

### publish message
POST http://localhost:8060/messages/publish
Content-Type: application/json

{
  "queue": "test",
  "payload": {
    "arg": "1234"
  }
}

### prepare message
POST http://localhost:8060/messages/prepare
Content-Type: application/json

{
  "queue": "test.result",
  "payload": {
    "arg": "1234"
  }
}

### release message
POST http://localhost:8060/messages/release?id=af88f155-3d13-47a5-9be3-73f829abec0c

### check message 1
GET http://localhost:8060/messages/check?id=35643438-12ca-4f28-ab8e-1215f92c221f

### check message 2
GET http://localhost:8060/messages/check?id=d8d4d0f7-1bbd-48c0-9f80-c66f5fd45fca

### check message not found
GET http://localhost:8060/messages/check?id=d8d4d0f7-1bbd-48c0-9f80-c66f5fd45fcb

### consume messages
POST http://localhost:8060/messages/consume?queue=test&limit=3

### consume messages (with poll)
POST http://localhost:8060/messages/consume?queue=test.result&limit=3&poll=25

### ack message
POST http://localhost:8060/messages/ack
Content-Type: application/json

[
  {
    "id": "117fd1c3-cce8-4afe-ae0e-8a0d28a62a4f",
    "release": []
  }
]

### nack message
POST http://localhost:8060/messages/nack
Content-Type: application/json

{
  "ids": ["af88f155-3d13-47a5-9be3-73f829abec0c"]
}
