### check health
GET http://localhost:8060/health

### publish message
POST http://localhost:8060/messages/publish
Content-Type: application/json

[
  {
    "queue": "test",
    "payload": "{\"arg\": \"1234\"}"
  }
]

### prepare message
POST http://localhost:8060/messages/prepare
Content-Type: application/json

[
  {
    "queue": "test.result",
    "payload": "{\"arg\": \"1234\"}"
  }
]

### release message
POST http://localhost:8060/messages/release
Content-Type: application/json

[
  "ad37b277-7e9d-43d5-bf6c-7b33ac7c3a50"
]

### check messages
POST http://localhost:8060/messages/check
Content-Type: application/json

[
  "70580c94-6b56-40b4-b022-299ef12786ea",
  "ad37b277-7e9d-43d5-bf6c-7b33ac7c3a50"
]

### consume messages
POST http://localhost:8060/messages/consume
Content-Type: application/json

{
  "queue": "test",
  "limit": 3
}

### consume messages (with poll)
POST http://localhost:8060/messages/consume
Content-Type: application/json

{
  "queue": "test.result",
  "limit": 3,
  "poll": 25
}

### ack message
POST http://localhost:8060/messages/ack
Content-Type: application/json

[
  {
    "id": "1b62104d-19fa-4de0-a43e-7a08ab30d765",
    "release": []
  },
  {
    "id": "9fdc61fb-52bb-4617-aaf6-f992c7e40010",
    "release": []
  }
]

### nack message
POST http://localhost:8060/messages/nack
Content-Type: application/json

[
  {
    "id": "308a0c72-75b1-47c5-9e93-59f134241787",
    "redeliver": false
  }
]

### redirect message
POST http://localhost:8060/messages/redirect
Content-Type: application/json

[
  {
    "id": "c12340ef-61a1-467a-8132-6b9cf00ceb45",
    "destination": "all_results"
  }
]
